[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = []
#ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
evm_version = "paris"   # required for slither to work

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
